SELECT
      T.TABLE_NAME TABLE_NAME,
      T.TABLE_DESC TABLE_DESC,
      T.COLNO      COL_NO,
      T.COLNAME    COL_NAME,
      CASE WHEN T.TYPENAME LIKE '%CHAR' THEN T.TYPENAME||'('||TRIM(CHAR(T.LENGTH))||')' WHEN T.TYPENAME LIKE 'DECIMAL%' THEN T.TYPENAME||'('||TRIM(CHAR(T.LENGTH))||','||TRIM(CHAR(T.SCALE))||')' ELSE T.TYPENAME END as DATA_TYPE,
      T.NULLS as NULLABLE,
      --CASE WHEN T.TYPENAME LIKE '%CHAR' THEN NULL WHEN T.TYPENAME LIKE 'DECIMAL%' THEN NULL ELSE T.LENGTH END as LENGTH,
      T.LENGTH as LENGTH,
      T.PM_KEY as KEY_IND,
      T.PT_KEY as PART_IND,
      T.INDX as IEX_IND,
      T.COLDESC as COL_DESC
  FROM
      (
       SELECT
              MAX(RTRIM(A0.TABSCHEMA)||'.'||RTRIM(A0.TABNAME)) TABLE_NAME, 
              VALUE(MAX(A0.REMARKS),'NULL') TABLE_DESC,
              A.COLNO + 1 AS COLNO,
              MAX(A.COLNAME) AS COLNAME,
              MAX(CASE WHEN A.TYPENAME = 'CHARACTER' THEN 'CHAR' ELSE A.TYPENAME END) AS TYPENAME,
              MAX(CASE WHEN A.TYPENAME = 'SMALLINT' THEN 5 WHEN A.TYPENAME = 'INTEGER' THEN 10 WHEN A.TYPENAME = 'BIGINT' THEN 19 ELSE A.LENGTH END) AS LENGTH,
              MAX(A.SCALE) AS SCALE,
              MAX(A.NULLS) AS NULLS,
              MAX(CASE WHEN C.COLNAME IS NOT NULL THEN '1' ELSE '0' END) AS PM_KEY,
              MAX(A.PARTKEYSEQ) AS PT_KEY,
              MAX(CASE WHEN D.COLNAMES IS NOT NULL THEN '1' ELSE '0' END) AS INDX,
              MAX(VALUE(A.REMARKS,'-')) AS COLDESC
         FROM SYSCAT.TABLES  A0
              LEFT JOIN SYSCAT.COLUMNS A
                        ON A.TABSCHEMA = A0.TABSCHEMA AND A.TABNAME = A0.TABNAME
              LEFT JOIN SYSCAT.TABCONST B
                        ON A.TABSCHEMA = B.TABSCHEMA AND A.TABNAME = B.TABNAME
              LEFT JOIN SYSCAT.KEYCOLUSE C
                        ON B.CONSTNAME = C.CONSTNAME AND A.COLNAME = C.COLNAME
              LEFT JOIN SYSCAT.INDEXES D
                        ON A.TABSCHEMA = D.TABSCHEMA AND A.TABNAME = D.TABNAME AND LOCATE(A.COLNAME,D.COLNAMES) <> 0
        WHERE 1 = 1
          AND A0.TABNAME = UPPER('$TabName')
          AND (A0.TABSCHEMA= UPPER('$TabSchema') or '$TabSchema' = 'TabSchema')
        GROUP BY A.COLNO
      ) T
ORDER BY T.COLNO
WITH UR
