import pexpect

# First time, fetch the verification code
c = pexpect.spawnu('vpn_prod.sh')
c.expect('Enter Auth Username:')
print(''.join(c.before), end='')
print(c.after, end='')
c.sendline('username')
c.expect('Enter Auth Password:')
print(''.join(c.before), end='')
print(c.after, end='')
c.sendline('password')
c.expect('Please input SMS verify code:')
print(''.join(c.before), end='')
print(c.after, end='')
c.sendline('')
c.expect(pexpect.EOF)
print(c.before, end='')
# c.kill(9)
print('is alive:', c.isalive())

# Second time, use the verification code to connect OpenVPN
c = pexpect.spawnu('vpn_prod.sh')
c.expect('Enter Auth Username:')
print(''.join(c.before), end='')
print(c.after, end='')
c.sendline('username')
c.expect('Enter Auth Password:')
print(''.join(c.before), end='')
print(c.after, end='')
c.sendline('password')
c.expect('Please input SMS verify code:')
print(''.join(c.before), end='')
print(c.after, end='')
c.interact()
# c.expect('Initialization Sequence Completed')
if c.isalive():
    c.close(force=False)
print('is alive:', c.isalive())
